FROM golang:1.13.5-alpine3.10 as builder
RUN apk update && apk upgrade && \
    apk add \
    xz-dev \
    musl-dev \
    gcc
RUN mkdir -p /go/src/github.com/mendersoftware/workflows
COPY . /go/src/github.com/mendersoftware/workflows
RUN cd /go/src/github.com/mendersoftware/workflows && \
    env CGO_ENABLED=0 go test -c -o workflows-test -coverpkg $(go list ./... | grep -v vendor | grep -v mocks | grep -v test | tr  '\n' ,)

FROM alpine:3.10
RUN apk update && apk upgrade && \
    apk add --no-cache ca-certificates xz
RUN mkdir -p /etc/workflows
COPY ./worker/config.yaml /etc/workflows/config.yaml
COPY --from=builder /go/src/github.com/mendersoftware/workflows/workflows-test /usr/bin
COPY ./worker/decommission_device.json /etc/workflows/definitions/decommission_device.json
COPY ./worker/provision_device.json /etc/workflows/definitions/provision_device.json
ENTRYPOINT [ \
    "/usr/bin/workflows-test", \
    "-test.coverprofile=/testing/coverage-acceptance-worker.txt", \
    "-acceptance-tests", \
    "-test.run=TestRunMain", \
    "-cli-args=--config=/etc/workflows/config.yaml worker --automigrate --workflows=decommission_device,provision_device --excluded-workflows=generate_artifact" \
]
