FROM golang:1.17.8-alpine3.15 as builder
RUN apk add --no-cache \
    xz-dev \
    musl-dev \
    gcc \
    ca-certificates
WORKDIR /go/src/github.com/mendersoftware/workflows
COPY ./ .
RUN env CGO_ENABLED=0 go test -c \
    -tags main -o workflows \
    -cover -covermode atomic \
    -coverpkg $(go list -deps | \
    grep '^github.com/mendersoftware/workflows' | \
    tr  '\n' ,)

FROM scratch
EXPOSE 8080
WORKDIR /etc/workflows
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /go/src/github.com/mendersoftware/workflows/workflows /usr/bin/

COPY ./config.yaml .
ENTRYPOINT [ \
    "/usr/bin/workflows", \
    "--config=/etc/workflows/config.yaml", \
    "server", \
    "--automigrate" \
    ]
