FROM golang:1.17.8-alpine3.15 as builder
RUN apk add --no-cache \
    xz-dev \
    musl-dev \
    gcc
WORKDIR /go/src/github.com/mendersoftware/workflows
COPY ./ .
RUN env CGO_ENABLED=0 go test -c \
    -tags main -o workflows \
    -cover -covermode atomic \
    -coverpkg $(go list -deps | \
    grep '^github.com/mendersoftware/workflows' | \
    tr  '\n' ,)

FROM alpine:3.15.3
RUN apk add --no-cache ca-certificates xz
COPY --from=builder /go/src/github.com/mendersoftware/workflows/workflows /usr/bin

RUN mkdir -p /etc/workflows
COPY ./config.yaml /etc/workflows
ENTRYPOINT [ \
    "/usr/bin/workflows", \
    "--config=/etc/workflows/config.yaml", \
    "server", \
    "--automigrate" \
    ]

EXPOSE 8080
